version: 2.1
executors:
  cypress-14-19-0:
    docker:
      - image: "cypress/base:14.19.0"
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install:
          executor: cypress-14-19-0
          # run a custom app build step
          install-command: 'yarn install --frozen-lockfile'
          build: 'yarn build'
      - cypress/run:
          # make sure app has been installed and built
          # before running tests across multiple machines
          # this avoids installing same dependencies 10 times
          executor: cypress-14-19-0
          requires:
            - cypress/install
          record: false # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'yarn start' # start server before running tests
          post-steps:
            - run: yarn test